import type { CSSProperties } from 'react'

import { Button, Container, Section, SectionHeader } from '../common'

type ValueStripSectionProps = {
  className?: string
}

const challenges = [
  'Manual Work',
  'Disconnected Systems',
  'Repetitive Tasks',
  'Slow Operations',
  'Scattered Data',
  'Legacy Software',
]

const engineStages = [
  'Business Challenges',
  'Software Platform',
  'AI Intelligence',
  'Automation',
  'Business Outcomes',
]

const outcomes = [
  'Faster Delivery',
  'AI Assisted Decisions',
  'Connected Systems',
  'Voice Automation',
  'Live Insights',
  'Automated Workflows',
  'Increased Productivity',
]

export function ValueStripSection({ className }: ValueStripSectionProps) {
  return (
    <Section className={['value-strip', className].filter(Boolean).join(' ')} spacing="compact">
      <Container>
        <div className="value-strip__layout">
          <div className="value-strip__content">
            <SectionHeader
              className="value-strip__header"
              description="We turn disconnected operations into connected software systems that reduce manual work, improve visibility, and help teams move faster."
              title="What We Help Businesses Achieve"
            />
            <Button className="value-strip__cta" href="/services" variant="ghost">
              See Our Services <span aria-hidden="true">-&gt;</span>
            </Button>
          </div>

          <div aria-label="Business transformation engine" className="value-strip__visual">
            <div aria-hidden="true" className="value-strip__mesh" />
            <div aria-hidden="true" className="value-strip__particles">
              <span />
              <span />
              <span />
              <span />
              <span />
            </div>

            <div className="value-strip__engine">
              <div className="value-strip__input" aria-label="Business challenges entering the AI engine">
                <p>Business Challenges</p>
                <ul>
                  {challenges.map((challenge, index) => (
                    <li key={challenge} style={{ '--item-index': index } as CSSProperties}>
                      {challenge}
                    </li>
                  ))}
                </ul>
              </div>

              <div className="value-strip__pipeline value-strip__pipeline--in" aria-hidden="true">
                <span className="value-strip__pipeline-line" />
                <span className="value-strip__pipeline-pulse" />
                <span className="value-strip__pipeline-particle value-strip__pipeline-particle--one" />
                <span className="value-strip__pipeline-particle value-strip__pipeline-particle--two" />
              </div>

              <div className="value-strip__core" aria-label="AI core processing business operations" tabIndex={0}>
                <span aria-hidden="true" className="value-strip__core-glow" />
                <span aria-hidden="true" className="value-strip__core-ring value-strip__core-ring--outer" />
                <span aria-hidden="true" className="value-strip__core-ring value-strip__core-ring--middle" />
                <span aria-hidden="true" className="value-strip__core-ring value-strip__core-ring--inner" />
                <span aria-hidden="true" className="value-strip__core-grid" />
                <div className="value-strip__core-label">
                  <span>AI Engine</span>
                  <strong>Processing</strong>
                </div>
                <ul className="value-strip__core-stages" aria-label="Transformation stages">
                  {engineStages.map((stage, index) => (
                    <li key={stage} style={{ '--stage-index': index } as CSSProperties}>
                      {stage}
                    </li>
                  ))}
                </ul>
              </div>

              <div className="value-strip__pipeline value-strip__pipeline--out" aria-hidden="true">
                <span className="value-strip__pipeline-line" />
                <span className="value-strip__pipeline-pulse" />
                <span className="value-strip__pipeline-particle value-strip__pipeline-particle--one" />
                <span className="value-strip__pipeline-particle value-strip__pipeline-particle--two" />
              </div>

              <div className="value-strip__output" aria-label="Business outcomes generated by the AI engine">
                <p>Business Outcomes</p>
                <ul>
                  {outcomes.map((outcome, index) => (
                    <li key={outcome} style={{ '--item-index': index } as CSSProperties}>
                      <span aria-hidden="true">✓</span>
                      {outcome}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </Section>
  )
}
